# Generated by Django 4.2.11 on 2024-06-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="comments",
            field=models.TextField(
                blank=True,
                default="あなたのことをありったけ書いてください！",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("other", "other"),
                    ("not_specified", "not_specified"),
                ],
                default="not_specified",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="place",
            field=models.TextField(
                blank=True, default="日本", max_length=1000, null=True
            ),
        ),
    ]
